# Generated by Django 4.2.11 on 2024-03-14 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taxis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'taxis',
            },
        ),
        migrations.CreateModel(
            name='trajectories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('taxi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.taxis')),
            ],
            options={
                'verbose_name_plural': 'trajectories',
            },
        ),
    ]
